artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://mydatasets1.s3.amazonaws.com/powerconsumption.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/powerconsumption.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/powerconsumption.csv

model_trainer:
  root_dir: artifacts/model_training
  features_data_path: artifacts/data_transformation/features.csv
  targets_data_path: artifacts/data_transformation/targets.csv
  model_name: model.joblib